scheduler:
    tasks:
        extract_data:
            cron_expression: "0 0 * * *"
            command: 'app:extract-data'
        transform_data:
            cron_expression: "0 1 * * *"
            command: 'app:transform-data'
        upload_sftp:
            cron_expression: "0 2 * * *"
            command: 'app:upload-to-sftp'
